module mol_tools
    !
    ! Tools to identify molecular types using a topology file 
    ! This code has been generated by Gemini 3.0
    !
    use mod_common, only: SystemType, SpeciesType, AtomMolMap, rigid, nmrigid, rigid_mols, &
                          & Tfact, nmzero, Nsites, topol
    use mod_input, only: ndim
    implicit none
    integer :: num_species
    type(SpeciesType), allocatable :: catalog(:)
contains
    
    subroutine set_equipartition_cte()
        integer :: s, tsum
        if (topol) then
            tsum = 0
            ! Degrees of freedom for temperature calculation
            do s = 1, num_species
                tsum = tsum + catalog(s)%count*(ndim+catalog(s)%rot_dof)
            end do
            if (rigid) then
                Tfact = tsum-nmzero*ndim
            else
                Tfact = (Nsites - nmzero - 1)*ndim
            endif
        else
            Tfact = (Nsites - nmzero - 1)*ndim
        endif
    end subroutine set_equipartition_cte
    
    subroutine identify_molecules(sys)
        type(SystemType), intent(inout) :: sys
        integer :: i, curr_mol, head_q, tail_q, u, v, e
        integer, allocatable :: queue(:)
        logical, allocatable :: visited(:)

        if (allocated(sys%mol_ids)) deallocate(sys%mol_ids)
        allocate(visited(sys%n_atoms))
        allocate(queue(sys%n_atoms))
        allocate(sys%mol_ids(sys%n_atoms))
        
        visited = .false.
        sys%mol_ids = 0
        curr_mol = 0

        do i = 1, sys%n_atoms
            if (.not. visited(i)) then
                curr_mol = curr_mol + 1
                head_q = 1
                tail_q = 1
                queue(tail_q) = i
                visited(i) = .true.
                sys%mol_ids(i) = curr_mol

                do while (head_q <= tail_q)
                    u = queue(head_q)
                    head_q = head_q + 1
                    e = sys%head(u)
                    do while (e > 0)
                        v = sys%adj(e)
                        if (.not. visited(v)) then
                            visited(v) = .true.
                            sys%mol_ids(v) = curr_mol
                            tail_q = tail_q + 1
                            queue(tail_q) = v
                        end if
                        e = sys%next(e)
                    end do
                end do
            end if
        end do
        sys%n_mols = curr_mol
        deallocate(visited, queue)
    end subroutine identify_molecules

    subroutine build_adjacency(sys, b1, b2)
        type(SystemType), intent(inout) :: sys
        integer, intent(in) :: b1(:), b2(:) 
        integer :: i, u, v, edge_cnt

        allocate(sys%head(sys%n_atoms))
        allocate(sys%next(2 * sys%n_bonds))
        allocate(sys%adj(2 * sys%n_bonds))
        sys%head = 0
        edge_cnt = 0

        do i = 1, sys%n_bonds
            u = b1(i)
            v = b2(i)
            edge_cnt = edge_cnt + 1
            sys%adj(edge_cnt) = v
            sys%next(edge_cnt) = sys%head(u)
            sys%head(u) = edge_cnt
            edge_cnt = edge_cnt + 1
            sys%adj(edge_cnt) = u
            sys%next(edge_cnt) = sys%head(v)
            sys%head(v) = edge_cnt
        end do
    end subroutine build_adjacency

    subroutine discover_species(sys)
        type(SystemType), intent(inout) :: sys
        integer, allocatable :: current_sig(:), cur_types(:), mol_to_spec(:)
        integer :: m, s
        logical :: found, linear_check

        allocate(catalog(sys%n_mols)) 
        allocate(mol_to_spec(sys%n_mols))
        num_species = 0

        do m = 1, sys%n_mols
             call get_mol_data(sys, m, current_sig, cur_types)
             found = .false.
             do s = 1, num_species
                if (signatures_match(current_sig, catalog(s)%signature)) then
                    catalog(s)%count = catalog(s)%count + 1
                    mol_to_spec(m) = s
                    found = .true.
                    exit
                end if
            end do

            if (.not. found) then
                num_species = num_species + 1
                mol_to_spec(m) = num_species
                catalog(num_species)%count = 1
                catalog(num_species)%num_atoms = size(current_sig)
                catalog(num_species)%member_types = cur_types
                allocate(catalog(num_species)%signature(size(current_sig)))
                catalog(num_species)%signature = current_sig
                
                linear_check = check_linearity(sys, m)
                catalog(num_species)%is_linear = linear_check
                if (ndim == 2) then
                    catalog(num_species)%rot_dof = 0
                    if (catalog(num_species)%num_atoms >1) then
                        catalog(num_species)%rot_dof = 1
                    end if
                else
                    if (catalog(num_species)%num_atoms == 1) then
                        catalog(num_species)%rot_dof = 0
                    else if (linear_check) then
                        catalog(num_species)%rot_dof = 2
                    else
                    catalog(num_species)%rot_dof = 3
                    end if
                endif
            end if
            deallocate(current_sig, cur_types)
        end do

        call build_atom_mapping(sys, catalog(1:num_species), mol_to_spec)

        print *, "Species ID | Atoms | Linear? | Rot. DOF | Population | Types"
        do s = 1, num_species
            print '(I10, "  | ", I5, " | ", L7, " | ", I8, " | ", I10," | ", 15I3)', &
                  s, catalog(s)%num_atoms, catalog(s)%is_linear, &
                  catalog(s)%rot_dof, catalog(s)%count, catalog(s)%member_types
        end do
        deallocate(mol_to_spec)
        print  '("Analysis complete.", I3, " molecular species identified, ",I5," molecules found")', num_species, sys%n_mols
        if (rigid) then
            print '("Rigid molecular types: ", 10I3)', rigid_mols(1:nmrigid)
        endif
    end subroutine discover_species

    subroutine build_atom_mapping(sys, catalog, mol_to_spec)
        type(SystemType), intent(inout) :: sys
        type(SpeciesType), intent(in) :: catalog(:)
        integer, intent(in) :: mol_to_spec(:)
        integer :: i, m_idx, s_idx

        if (allocated(sys%map)) deallocate(sys%map)
        allocate(sys%map(sys%n_atoms))

        do i = 1, sys%n_atoms
            m_idx = sys%mol_ids(i)
            s_idx = mol_to_spec(m_idx)
            sys%map(i)%mol_id   = sys%lammps_mol_tags(i)
            sys%map(i)%mol_type = s_idx
            sys%map(i)%rot_df   = catalog(s_idx)%rot_dof
        end do
    end subroutine build_atom_mapping

    subroutine get_mol_data(sys, mol_idx, signature, types)
        type(SystemType), intent(in) :: sys
        integer, intent(in) :: mol_idx
        integer, allocatable, intent(out) :: signature(:), types(:)
        integer :: i, j, a, e, neighbor, n_in_mol
        integer, allocatable :: mol_atoms(:)
        
        n_in_mol = count(sys%mol_ids == mol_idx)
        allocate(mol_atoms(n_in_mol), signature(n_in_mol), types(n_in_mol))
        
        j = 1
        do i = 1, sys%n_atoms
            if (sys%mol_ids(i) == mol_idx) then
                mol_atoms(j) = i
                types(j) = sys%atom_types(i)
                j = j + 1
            end if
        end do
        
        do i = 1, n_in_mol
            a = mol_atoms(i)
            signature(i) = sys%atom_types(a) * 100
            e = sys%head(a)
            do while (e > 0)
                neighbor = sys%adj(e)
                signature(i) = signature(i) + sys%atom_types(neighbor)
                e = sys%next(e)
            end do
        end do
        
        call bubble_sort(signature)
        call bubble_sort(types)
        deallocate(mol_atoms)
    end subroutine get_mol_data

    function check_linearity(sys, mol_idx) result(is_linear)
        type(SystemType), intent(in) :: sys
        integer, intent(in) :: mol_idx
        logical :: is_linear
        integer :: a, e, n_count
        
        is_linear = .true.
        do a = 1, sys%n_atoms
            if (sys%mol_ids(a) == mol_idx) then
                n_count = 0
                e = sys%head(a)
                do while (e > 0)
                    n_count = n_count + 1
                    e = sys%next(e)
                end do
                if (n_count > 2) then
                    is_linear = .false.
                    return
                end if
            end if
        end do
    end function check_linearity

    subroutine bubble_sort(arr)
        integer, intent(inout) :: arr(:)
        integer :: i, j, temp, n
        n = size(arr)
        do i = 1, n-1
            do j = 1, n-i
                if (arr(j) > arr(j+1)) then
                    temp = arr(j)
                    arr(j) = arr(j+1)
                    arr(j+1) = temp
                end if
            end do
        end do
    end subroutine bubble_sort

    function signatures_match(sig1, sig2) result(match)
        integer, intent(in) :: sig1(:), sig2(:)
        logical :: match
        integer :: i
        match = .false.
        if (size(sig1) /= size(sig2)) return
        do i = 1, size(sig1)
            if (sig1(i) /= sig2(i)) return
        end do
        match = .true.
    end function signatures_match

end module mol_tools

subroutine read_lammps_data(filename, sys)
    use mol_tools
    implicit none
    character(len=*), intent(in) :: filename
    type(SystemType), intent(inout) :: sys
    integer :: ios, i, dummy_id
    character(len=200) :: line
    integer, allocatable :: b1(:), b2(:)

    open(unit=10, file=filename, status='old', action='read', iostat=ios)
    if (ios /= 0) stop "Error opening file"

    sys%n_atoms = 0
    sys%n_bonds = 0
    do
        read(10, '(A)', iostat=ios) line
        if (ios /= 0) exit
        if (index(line, "atoms") > 0 .and. sys%n_atoms == 0) read(line, *) sys%n_atoms
        if (index(line, "bonds") > 0 .and. sys%n_bonds == 0) read(line, *) sys%n_bonds
        if (index(line, "Atoms") > 0) exit
    end do

    allocate(sys%atom_types(sys%n_atoms))
    allocate(sys%lammps_mol_tags(sys%n_atoms))
    allocate(b1(sys%n_bonds), b2(sys%n_bonds))

    do i = 1, sys%n_atoms
        read(10, *) dummy_id, sys%lammps_mol_tags(i), sys%atom_types(i)
    end do

    rewind(10)
    do
        read(10, '(A)', iostat=ios) line
        if (index(line, "Bonds") > 0) exit
    end do

    do i = 1, sys%n_bonds
        read(10, *) dummy_id, dummy_id, b1(i), b2(i)
    end do
    close(10)

    call build_adjacency(sys, b1, b2)
    deallocate(b1, b2)
end subroutine read_lammps_data

subroutine define_molecules()
    use mod_common
    use mod_input, only: system_data_file
    use mol_tools
    implicit none
    
    call read_lammps_data(system_data_file, my_sys)
    call identify_molecules(my_sys)   
    call discover_species(my_sys)
end subroutine define_molecules
